/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Category;
import model.Ghe;
import service.CategoryService;
import service.GheService;
import service.IventoryLogService;

/**
 *
 * @author hodangquan
 */
public class NhapXuatForm extends javax.swing.JFrame {

    /**
     * Creates new form NhapXuatForm
     */
    private CategoryService categoryService;
    private GheService gheService;
    private IventoryLogService iventoryLogService;

    public NhapXuatForm() {

        initComponents();
        categoryService = new CategoryService();
        gheService = new GheService();
        iventoryLogService = new IventoryLogService();
        rbNhap.setSelected(true);
        rbXuat.setSelected(false);

        List<Category> categorys = categoryService.layAllCategory();
        cbbDanhMuc.removeAllItems();
        for (Category category : categorys) {
            cbbDanhMuc.addItem(category.getCategoryName());

        }

    }

    public void hienThi() {
        try {
            cbbSanPham.removeAllItems();
            Integer id = null;
            String danhMuc = (String) cbbDanhMuc.getSelectedItem();
            List<Category> categorys = categoryService.layAllCategory();
            for (Category category : categorys) {
                if (danhMuc.equals(category.getCategoryName())) {
                    id = category.getId();
                }
            }
            List<Ghe> ghe1s = gheService.layDSXeDapByCategory(id);
            for (Ghe ghe1 : ghe1s) {
                if (ghe1.isKhaDung() == true) {
                    cbbSanPham.addItem(ghe1.getTen());
                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbDanhMuc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbSanPham = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbNhap = new javax.swing.JRadioButton();
        rbXuat = new javax.swing.JRadioButton();
        btnThucHien = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Nhập Xuất");

        jLabel2.setText("Danh Mục");

        cbbDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDanhMucActionPerformed(evt);
            }
        });

        jLabel3.setText("Sản Phẩm");

        cbbSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSanPhamActionPerformed(evt);
            }
        });

        jLabel4.setText("Trạng Thái");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel5.setText("Số Lượng");

        buttonGroup1.add(rbNhap);
        rbNhap.setText("Nhập");

        buttonGroup1.add(rbXuat);
        rbXuat.setText("Xuất");

        btnThucHien.setText("Thực Hiện");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThucHien)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(rbNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbNhap)
                    .addComponent(rbXuat)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThucHien)
                    .addComponent(btnHuy))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        // TODO add your handling code here:
        String so = "^[-?0-9\\.]*$";
        String chu = "^[a-zA-Z]*$";
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chắc là số lượng không được chứa khoảng trắng đâu :)) ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!txtSoLuong.getText().matches(so)) {
            JOptionPane.showMessageDialog(this, "Chắc là số lượng phải nhập toàn số cơ  :)) ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtSoLuong.getText().length() >= 30) {
            JOptionPane.showMessageDialog(this, "Chắc là độ vượt quá độ dài cho phép rồi :)) ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String soLuongString = txtSoLuong.getText().replaceAll("[-]{2}", "");
        if (soLuongString.isEmpty() || soLuongString.equalsIgnoreCase("-")) {
            JOptionPane.showMessageDialog(this, "Chắc số lượng phải là số rồi :)) ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtSoLuong.getText().contains(",")) {
            JOptionPane.showMessageDialog(this, "Chắc Số lượng không được chứa dấu phẩy Rồi  . Vui lòng nhập lại số nguyên!", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double soluong = Double.parseDouble(soLuongString);
        if (Math.floor(soluong) != soluong) {
            JOptionPane.showMessageDialog(this, "Chắc là số lượng phải nhập số nguyên cơ :)) ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (soluong <= 0) {
            JOptionPane.showMessageDialog(this, "Chắc số lượng phải lớn hơn 0 cơ :(( ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (soluong >= 1000) {
            JOptionPane.showMessageDialog(this, "Chắc số lượng chỉ nhỏ hơn 1000 thôi:(( ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int soLuongUpdate = (int) Math.round(soluong);
        Integer id = null;
        BigDecimal gia = null;
        String idSanPham = (String) cbbSanPham.getSelectedItem();
        List<Ghe> ghes = gheService.layAllXeDaps();
        for (Ghe ghe : ghes) {
            if (idSanPham.equals(ghe.getTen())) {
                id = ghe.getId();
                gia = ghe.getGia();
            }
        }

        Integer soLuongHienTai = null;
        String sanpham = (String) cbbSanPham.getSelectedItem();
        List<Ghe> ghe1s = gheService.layAllXeDaps();
        for (Ghe ghe1 : ghe1s) {
            if (idSanPham.equals(ghe1.getTen())) {
                soLuongHienTai = ghe1.getSoLuong();
            }
        }
        if (rbNhap.isSelected() == true) {
            try {
                if (gheService.nhap(id, soLuongUpdate) == true) {
                    Integer soLuongNhap = soLuongHienTai + soLuongUpdate;
                    JOptionPane.showMessageDialog(this, "Nhập Thành công rồi :)) \n Số Lượng hiện tại trong kho là: " + soLuongNhap);
//                    themBaoCao();
                } else {
                    JOptionPane.showMessageDialog(this, "chắc là nhập thất bại rồi:)) ");
                }
            } catch (Exception e) {
            }
            return;
        }
        if (rbXuat.isSelected() == true) {
            try {
                if (gheService.checkSL(id, soLuongUpdate) == false) {
                    JOptionPane.showMessageDialog(this, "Chắc là số lượng xuất vượt quá số lượng hiện có rồi :))  \n Số Lượng hiện tại trong kho là:  " + soLuongHienTai);
                } else {
                    Integer soLuongXuat = soLuongHienTai - soLuongUpdate;
                    if (gheService.xuat(id, soLuongUpdate) == true) {
                        JOptionPane.showMessageDialog(this, "chắc Xuất Thành công rồi :)) \n Số Lượng hiện tại trong kho là: " + soLuongXuat);
                        themBaoCao();
                    } else {
                        JOptionPane.showMessageDialog(this, "chắc là Xuất thất bại rồi:)) ");
                    }

                }
            } catch (Exception e) {
                return;
            }
        }

    }//GEN-LAST:event_btnThucHienActionPerformed
    public void themBaoCao() {
        try {
            Integer id = null;
            Integer soLuongTon = null;
            String idSanPham = (String) cbbSanPham.getSelectedItem();
            List<Ghe> ghes = gheService.layAllXeDaps();
            for (Ghe ghe : ghes) {
                if (idSanPham.equals(ghe.getTen())) {
                    id = ghe.getId();
                    soLuongTon = ghe.getSoLuong();
                }
            }
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM-dd-yyyy");
            ZonedDateTime now = ZonedDateTime.now();
            String time = dtf.format(now);
            String soLuongString1 = txtSoLuong.getText().replaceAll("[-]{2}", "");
            double soLuong = Double.parseDouble(soLuongString1);
            int soLuongUpdate = (int) Math.round(soLuong);
            Integer soLuongNhap = 0;
            Integer soLuongXuat = 0;
            if (rbNhap.isSelected() == true) {
                soLuongNhap = soLuongUpdate;
                soLuongXuat = 0;

            } else {
                soLuongNhap = 0;
                soLuongXuat = soLuongUpdate;
            }
            iventoryLogService.themBaoCao(id, time, soLuongXuat);
        } catch (Exception e) {
            
        }
    }

    private void cbbDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDanhMucActionPerformed
        // TODO add your handling code here:
        hienThi();
    }//GEN-LAST:event_cbbDanhMucActionPerformed

    private void cbbSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSanPhamActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapXuatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThucHien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbDanhMuc;
    private javax.swing.JComboBox<String> cbbSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rbNhap;
    private javax.swing.JRadioButton rbXuat;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

}
