/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Ghe;
import service.CategoryService;
import service.GheService;
import service.IdUpdateService;

/**
 *
 * @author hodangquan
 */
public class QuanLyForm extends javax.swing.JFrame {

    private CategoryService categoryService;
    private GheService gheService;

    public QuanLyForm() {
        initComponents();
        categoryService = new CategoryService();
        gheService = new GheService();
        hienthi();
        List<Category> categorys = categoryService.layAllCategory();
        cbbTimTheoTheLoai.removeAllItems();
        for (Category category : categorys) {
            cbbTimTheoTheLoai.addItem(category.getCategoryName());

        }
    }

    public void hienthi() {
        DefaultTableModel model = (DefaultTableModel) tbGhe.getModel();
        model.setRowCount(0);
        List<Ghe> ghes = gheService.layAllXeDaps();
        List<Category> categorys = categoryService.layAllCategory();
        String tenDanhMuc = "";
        for (Ghe ghe : ghes) {
            for (Category category : categorys) {
                if (category.getId() == ghe.getCategoryId()) {
                    tenDanhMuc = category.getCategoryName();
                }
            }
            if (ghe.isKhaDung() == true) {
                Object[] data = new Object[]{
                    ghe.getId(),
                    tenDanhMuc,
                    ghe.getTen(),
                    ghe.getGia(),
                    ghe.getSoLuong(),
                    ghe.getKichThuoc(),
                    ghe.getXuatSu()
                };
                model.addRow(data);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGhe = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbbTimTheoTheLoai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTimTheoTen = new javax.swing.JTextField();
        btnTimTheoTen = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnBaoCao = new javax.swing.JButton();
        btnTimTheoTheLoai = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Quản Lý");

        tbGhe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Danh Mục", "Tên", "Giá", "Số Lượng", "Kích Thước", "Xuất Sứ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbGhe);

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm Theo Danh Mục");

        cbbTimTheoTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbTimTheoTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimTheoTheLoaiActionPerformed(evt);
            }
        });

        jLabel3.setText("Tìm Theo Tên");

        txtTimTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimTheoTenActionPerformed(evt);
            }
        });

        btnTimTheoTen.setText("Tìm");
        btnTimTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheoTenActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnBaoCao.setText("Báo Cáo");
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });

        btnTimTheoTheLoai.setText("Tìm");
        btnTimTheoTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheoTheLoaiActionPerformed(evt);
            }
        });

        btnThoat.setText("Ấn vào đây để Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSua)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBaoCao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbbTimTheoTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTimTheoTheLoai))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnTimTheoTen)))))
                                .addGap(27, 27, 27)))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnBaoCao))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbTimTheoTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimTheoTheLoai))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimTheoTen)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimTheoTenActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTimTheoTenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ThemForm themForm = new ThemForm();
        themForm.setVisible(true);

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int index = tbGhe.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm trước khi sửa đê :))");
            return;
        }
        String idString = tbGhe.getValueAt(index, 0).toString();
        Integer id = Integer.parseInt(idString);
        IdUpdateService idUpdateService = new IdUpdateService();
        idUpdateService.setId(id);
        SuaForm sf = new SuaForm();
        sf.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int index = tbGhe.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm trước khi xóa đê :)) ");
                return;
            }
            int index1 = tbGhe.getRowCount();
            if (index1 == 0) {
                JOptionPane.showMessageDialog(this, "Không có dữ kiệu có dữ liệu để xóa :))");
                return;
            }
            int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa khum ? ");
            if (check != JOptionPane.YES_OPTION) {
                return;
            } else {
                String idString = tbGhe.getValueAt(index, 0).toString();
                Integer id = Integer.parseInt(idString);
                if (gheService.xoa(id) == true) {
                    JOptionPane.showMessageDialog(this, "CHắc là xóa thành công rồi :)) ");

                } else {
                    JOptionPane.showMessageDialog(this, " Chắc là Xóa thất bại rồi :))");
                }
                hienthi();
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoCaoActionPerformed
        // TODO add your handling code here:
        BaoCaoForm baoCaoForm = new BaoCaoForm();
        baoCaoForm.setVisible(true);
    }//GEN-LAST:event_btnBaoCaoActionPerformed

    private void cbbTimTheoTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimTheoTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTimTheoTheLoaiActionPerformed

    private void btnTimTheoTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTheoTheLoaiActionPerformed
        // TODO add your handling code here:
        timTheoDanhMuc();
    }//GEN-LAST:event_btnTimTheoTheLoaiActionPerformed

    private void btnTimTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTheoTenActionPerformed
        if (txtTimTheoTen.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập trước khi tìm kiếm :)) ");
            return;
        }

        try {
            String danhMuc = "";
            String search = txtTimTheoTen.getText();
            // TODO add your handling code here:
            List<Ghe> ghes = gheService.searchbyTen(search);
            DefaultTableModel model = (DefaultTableModel) tbGhe.getModel();
            model.setRowCount(0);
            List<Category> categorys = categoryService.layAllCategory();
            for (Category category : categorys) {
                if (danhMuc.equals(category.getCategoryName())) {

                }
            }
            for (Ghe ghe : ghes) {
                for (Category category : categorys) {
                    if (category.getId() == ghe.getCategoryId()) {
                        danhMuc = category.getCategoryName();
                    }
                }
                Object[] data = new Object[]{
                    ghe.getId(),
                    danhMuc,
                    ghe.getTen(),
                    ghe.getGia(),
                    ghe.getSoLuong(),
                    ghe.getKichThuoc(),
                    ghe.getXuatSu()
                };
                model.addRow(data);
            }
            if (tbGhe.getRowCount() > 0) {
                JOptionPane.showMessageDialog(this, "Chắc là tìm kiếm thành công rồi :)) ");
                return;

            }
            if (tbGhe.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Chắc là thông tin tìm kiếm không khợp với bạn ghi nào rồi :))");
                hienthi();

            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTimTheoTenActionPerformed

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        // TODO add your handling code here:
        hienthi();

    }//GEN-LAST:event_btnThemMouseExited

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
        // TODO add your handling code here:
        hienthi();
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    public void timTheoDanhMuc() {
        try {
            String danhMuc = (String) cbbTimTheoTheLoai.getSelectedItem();
            Integer id = null;
            List<Category> categorys = categoryService.layAllCategory();
            for (Category category : categorys) {
                if (danhMuc.equals(category.getCategoryName())) {
                    id = category.getId();
                }
            }
            DefaultTableModel model = (DefaultTableModel) tbGhe.getModel();
            model.setRowCount(0);

            List<Ghe> ghes = gheService.searchbyCategory(id);

            for (Ghe ghe : ghes) {
                Object[] data = new Object[]{
                    ghe.getId(),
                    danhMuc,
                    ghe.getTen(),
                    ghe.getGia(),
                    ghe.getSoLuong(),
                    ghe.getKichThuoc(),
                    ghe.getXuatSu()
                };
                model.addRow(data);
            }
            JOptionPane.showMessageDialog(this, "Chắc là tìm kiếm thành công rồi :))");
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimTheoTen;
    private javax.swing.JButton btnTimTheoTheLoai;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTimTheoTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbGhe;
    private javax.swing.JTextField txtTimTheoTen;
    // End of variables declaration//GEN-END:variables
}
