/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import model.Category;
import model.Ghe;
import service.CategoryService;
import service.GheService;

/**
 *
 * @author hodangquan
 */
public class ThemForm extends javax.swing.JFrame {

    /**
     * Creates new form ThemForm
     */
    private CategoryService categoryService;
    private GheService gheService;

    public ThemForm() {
        initComponents();

        categoryService = new CategoryService();
        gheService = new GheService();
        List<Category> categorys = categoryService.layAllCategory();
        cbbTheLoai.removeAllItems();
        for (Category category : categorys) {
            cbbTheLoai.addItem(category.getCategoryName());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtKichThuoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtXuatSu = new javax.swing.JTextField();
        cbbTheLoai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Số Lượng");

        txtKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKichThuocActionPerformed(evt);
            }
        });

        jLabel6.setText("Kích Thước");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Thêm Sản Phẩm");

        txtXuatSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXuatSuActionPerformed(evt);
            }
        });

        cbbTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Xuất Sứ");

        jLabel2.setText("Thể Loại");

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        jLabel4.setText("Giá");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtKichThuoc, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtXuatSu)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThoat)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtXuatSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnThem))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKichThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKichThuocActionPerformed

    private void txtXuatSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXuatSuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXuatSuActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String so = "^[-?0-9\\.]*$";
        String chu = "^[a-zA-Z\\s]*$";
        String ten = txtTen.getText().trim();
        String khoangTrang = txtGia.getText().trim();
        String quantityString = txtSoLuong.getText().trim();
        String size = txtKichThuoc.getText().trim();
        String origin = txtXuatSu.getText().trim();
        if (ten.isEmpty() || khoangTrang.isEmpty() || quantityString.isEmpty() || size.isEmpty() || origin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chắc là khong được bỏ trống đâu :))");
            return;
        }
        if (khoangTrang.replaceAll("[^ ]", "").length() > 0) {
            JOptionPane.showMessageDialog(this, "Chắc Giá phải viết liền và không được chứa khoảng trắng đâu . Vui lòng xóa các khoảng trắng đê :))) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (quantityString.replaceAll("[^ ]", "").length() > 0) {
            JOptionPane.showMessageDialog(this, "Chắc Số lượng phải viết liền và không được chứa khoảng trắng đâu . Vui lòng xóa các khoảng trắng đê :))) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (size.replaceAll("[^ ]", "").length() > 0) {
            JOptionPane.showMessageDialog(this, "Chắc Kích thước phải viết liền và không được chứa khoảng trắng đâu . Vui lòng xóa các khoảng trắng đê :)))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (quantityString.length() >= 20) {
            JOptionPane.showMessageDialog(this, "Chắc là Độ dài số lượng vượt quá độ dài cho phép rồi :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ten.length() >= 30) {
            JOptionPane.showMessageDialog(this, "Chắc là Độ dài Tên vượt quá độ dài cho phép rồi :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (khoangTrang.length() >= 20) {
            JOptionPane.showMessageDialog(this, "chắc là Độ dài Giá vượt quá độ dài cho phép rồi :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (origin.length() >= 20) {
            JOptionPane.showMessageDialog(this, "chắc là Độ dài Xuất sứ vượt quá độ dài cho phép rồi ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String soLuongString = quantityString.replaceAll("[-]{2}", "");
        if (soLuongString.isEmpty() || soLuongString.equalsIgnoreCase("-")) {
            JOptionPane.showMessageDialog(this, "Chắc là Số lương phải là số cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (soLuongString.contains(",")) {
            JOptionPane.showMessageDialog(this, "Chắc là số lượng không được chứa dấu ',' đâu :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!soLuongString.matches(so)) {
            JOptionPane.showMessageDialog(this, "Chắc là số lương phải là số cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double soLuong = Double.parseDouble(soLuongString);
        if (Math.floor(soLuong) != soLuong) {
JOptionPane.showMessageDialog(this, "Số lương phải là số nguyên cơ :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (soLuong <= 0) {
            JOptionPane.showMessageDialog(this, "Chắc là số lượng phải lớn hơn 0 cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (soLuong >= 1000) {
            JOptionPane.showMessageDialog(this, "Chắc là số lượng phải nhỏ hơn 1000 cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int soLuongUpdate = (int) Math.round(soLuong);

        if (size.length() >= 20) {
            JOptionPane.showMessageDialog(this, "Chắc là độ dài kích thước vượt quá độ dài cho phép rồi :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String sizeString = size.replaceAll("[-]{2}", "");
        if (sizeString.isEmpty() || sizeString.equalsIgnoreCase("-")) {
            JOptionPane.showMessageDialog(this, "Chắc là Kích thước phải là số cơ :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (sizeString.contains(",")) {
            JOptionPane.showMessageDialog(this, "CHắc là kích thước không được chứa dấu ',' đâu :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!sizeString.matches(so)) {
            JOptionPane.showMessageDialog(this, "chắc là Kích thước là số cơ :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double sizedb = Double.parseDouble(sizeString);
        if (Math.floor(sizedb) != sizedb) {
            JOptionPane.showMessageDialog(this, "Chắc là kích thước phải là số nguyên cơ :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (sizedb <= 0) {
            JOptionPane.showMessageDialog(this, "Chắc là kích thước phải lớn hơn 0 cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (sizedb >= 30) {
            JOptionPane.showMessageDialog(this, "Chắc là kích thước phải nhỏ hơn 30 cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!origin.matches(chu)) {
            JOptionPane.showMessageDialog(this, "Chắc là xuất sứ phải là chữ cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String priceCheck = khoangTrang.replaceAll("[-]{2}", "");
        if (priceCheck.isEmpty() || priceCheck.equalsIgnoreCase("-")) {
            JOptionPane.showMessageDialog(this,  "Chắc là giá phải là số cơ :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (khoangTrang.contains(",")) {
            JOptionPane.showMessageDialog(this, "chắc là giá không được chứa đấu ',' cơ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!khoangTrang.matches(so)) {
            JOptionPane.showMessageDialog(this, "Chắc là giá phải là số cơ ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double pricedb = Double.parseDouble(priceCheck);
        if (pricedb <= 0) {
            JOptionPane.showMessageDialog(this, "Chắc là giá phải lớn hơn không 0  cơ :)) ", "Thong Bao", JOptionPane.ERROR_MESSAGE);
return;
        }
        if (pricedb >= 99999999) {
            JOptionPane.showMessageDialog(this, "Chắc là giá nhỏ hơn 99999999 cơ :))", "Thong Bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        if(!origin.matches(chu)){
//            JOptionPane.showMessageDialog(this, "chắc là giá số cơ :)))");
//            return;
//            
//        }
        
        int sizeUpdate = (int) Math.round(sizedb);
        try {
            String Category = (String) cbbTheLoai.getSelectedItem();
            Integer CategoryId = null;
            List<Category> categorys = categoryService.layAllCategory();
            for (Category category : categorys) {
                if (Category.equals(category.getCategoryName())) {
                    CategoryId = category.getId();
                }
            }
            String name = txtTen.getText();
            BigDecimal price = BigDecimal.valueOf(pricedb);
            // TODO add your handling code here:
            Ghe g = new Ghe(0, CategoryId, name, price, soLuongUpdate, sizeUpdate, origin,true);
            if (gheService.them(g) == true) {
                JOptionPane.showMessageDialog(this, "Thêm Thành Công ");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất bại ");
            }
            QuanLyForm qlf = new QuanLyForm();
            qlf.hienthi();
            this.dispose();
        } catch (Exception e) {
        }
    

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbbTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtKichThuoc;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtXuatSu;
    // End of variables declaration//GEN-END:variables
}
